"""init schema

Revision ID: 80508c7975c3
Revises: 
Create Date: 2026-07-22 22:03:51.439731

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80508c7975c3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos_de_teste',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defeitos',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('ambiente', sa.String(length=60), nullable=False),
    sa.Column('passos_reproducao', sa.Text(), nullable=False),
    sa.Column('resultado_esperado', sa.Text(), nullable=False),
    sa.Column('resultado_obtido', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('responsavel', sa.String(length=120), nullable=False),
    sa.Column('criado_por', sa.String(length=120), nullable=False),
    sa.Column('caso_de_teste_id', sa.String(length=40), nullable=True),
    sa.Column('execucao_id', sa.String(length=40), nullable=True),
    sa.Column('pull_request', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defeitos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defeitos_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_defeitos_status'), ['status'], unique=False)

    op.create_table('execucoes',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('resultado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('evidencias',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('defeito_id', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['defeito_id'], ['defeitos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidencias_defeito_id'), ['defeito_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidencias_defeito_id'))

    op.drop_table('evidencias')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('execucoes')
    with op.batch_alter_table('defeitos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defeitos_status'))
        batch_op.drop_index(batch_op.f('ix_defeitos_codigo'))

    op.drop_table('defeitos')
    op.drop_table('casos_de_teste')
    # ### end Alembic commands ###
